AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-postgresql

  Sample SAM Template for lambda-postgresql
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        PGHOST: "" 
        PGDATABASE: "" 
        PGPASSWORD: "" 
        PGUSER: ""
    CodeUri: postgresql-adapter/
    Runtime: nodejs12.x
    Layers: 
        - "arn:aws:lambda:layer:nodePostgres:1"
    VpcConfig:
      SecurityGroupIds:
        - sg
      SubnetIds:
        - subnet
        - subnet
        - subnet
    Tags:
      Environment: "Prod"
      Application: "lambda-postgresql"
  Api:
    Auth:
      DefaultAuthorizer: AWS_IAM  

Resources:
  PostgresqlSelectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.pgSelectHandler
      Events:
        PostgresqlSelectAdapter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items
            Method: get

  PostgresqlCreateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.pgCreateHandler
      Events:
        PostgresqlCreateAdapter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PostgresqlSelectAdapterApi:
    Description: "API Gateway endpoint URL for Prod stage for Postgresql Query function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
  PostgresqlSelectFunction:
    Description: "Postgresql Query Lambda Function ARN"
    Value: !GetAtt PostgresqlSelectFunction.Arn
  PostgresqlSelectFunctionIamRole:
    Description: "Implicit IAM Role created for Postgresql Query function"
    Value: !GetAtt PostgresqlSelectFunctionRole.Arn
  PostgresqlCreateAdapterApi:
    Description: "API Gateway endpoint URL for Prod stage for Postgresql Query function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
  PostgresqlCreateFunction:
    Description: "Postgresql Query Lambda Function ARN"
    Value: !GetAtt PostgresqlCreateFunction.Arn
  PostgresqlCreateFunctionIamRole:
    Description: "Implicit IAM Role created for Postgresql Query function"
    Value: !GetAtt PostgresqlCreateFunctionRole.Arn